# Chapter 2.2 - Exercise 2: Hãy thực hiện những yêu cầu liên quan tới Data Frame

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Câu 1: Cho dictionary như sau:
dic_1 = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86], 'Z':[86,97,96,72,83]}

# Tạo dataframe df1 từ dic_1
df1 = pd.DataFrame(dic_1)
# In nội dung của dataframe df1
print(df1)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [5]:
# Câu 2:
# Cho dictionary exam_data như sau:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5,np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

# Cho list labels như sau:
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [6]:
# Câu 2a: Tạo dataframe df2 từ exam_data, với index của dataframe là lables
df2 = pd.DataFrame(exam_data,index = labels)

# In nội dung của dataframe df2
print(df2)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [7]:
# Câu 2b: Xem thông tin (info()) của dataframe df2

print(df2.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None

In [17]:
# Câu 3: Tạo dataframe df3 từ df2, chỉ chứa 2 cột là name và score
df3= df2.loc[:,['name','score']]
# Xem kiểu dữ liệu (type) và kích thước (shape) của df3
print(type(df3))
print(df3.shape)
# Hiển thị các dòng dữ liệu đầu tiên (head) của df3
print(df3.head())

<class 'pandas.core.frame.DataFrame'>
(10, 2)
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0

In [18]:
# Câu 4: Hiển thị thông tin thống kê chung (describe) của dataframe df2
print(df3.describe(include='all'))

             name      score
count          10   8.000000
unique         10        NaN
top     Anastasia        NaN
freq            1        NaN
mean          NaN  13.562500
std           NaN   4.693746
min           NaN   8.000000
25%           NaN   9.000000
50%           NaN  13.500000
75%           NaN  17.125000
max           NaN  20.000000

In [19]:
# Câu 5: Tạo dataframe df4 từ df2, chỉ chứa 2 cột là name và score, và chỉ có các dòng 1, 3, 5, 6
df4= df2.iloc[[1,3,5,6],[0,1]]
# In nội dung của dataframe df4
print(df4)

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

In [21]:
# Câu 6: Từ dataframe df2, in các dòng có dữ liệu score bị null
df2.loc[df2['score'].isnull() ,: ]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [23]:
# Câu 7: Từ dataframe df2, in các dòng có score > 15 và <=20
df2.loc[ (df2['score'] > 15) & (df2['score'] <= 20) ,:]

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

In [26]:
# Câu 8: Cập nhật điểm (score) ở dòng 'd' thành 18
df2.loc['d','score'] = 18
df2

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   18.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [32]:
# Câu 9: Cho biết điểm (score) nào có tần suất xuất hiện nhiều nhất trong df2, và in ra những dòng có điểm là tần suất xuất hiện nhiều nhất
df2.loc[:,'score'].mode()
df2.loc[df2['score'] == 9 ,:]

#c2
df2['score'].value_counts()

score
9.0     2
12.5    1
16.5    1
18.0    1
20.0    1
14.5    1
8.0     1
19.0    1
Name: count, dtype: int64

In [33]:
# Câu 10: Thêm dòng k có nội dung như sau: ['Suresh', 15.5, 1, 'yes'] vào df2
df2.loc['k'] = ['Suresh', 15.5, 1, 'yes']
# Hiển thị 5 dòng cuối cùng (tail) của df2.
print(df2.tail(5))

      name  score  attempts qualify
g  Matthew   14.5         1     yes
h    Laura    NaN         1      no
i    Kevin    8.0         2      no
j    Jonas   19.0         1     yes
k   Suresh   15.5         1     yes

In [34]:
# Câu 11a: Thêm dòng l có nội dung như sau: ['Janny', 12.5, 2, 'yes'] vào df2.
df2.loc['l'] = ['Janny', 12.5, 2, 'yes']
# Hiển thị 5 dòng cuối cùng (tail) của df2.
df2.tail(5)

     name  score  attempts qualify
h   Laura    NaN         1      no
i   Kevin    8.0         2      no
j   Jonas   19.0         1     yes
k  Suresh   15.5         1     yes
l   Janny   12.5         2     yes

In [44]:
# Câu 11b: Xóa bỏ dòng l của df2.

#df2 = df2.drop(['l'])
# Hiển thị lại 5 dòng cuối cùng (tail) của df2.
df2.tail(5)

      name  score  attempts qualify
g  Matthew   14.5         1     yes
h    Laura    NaN         1      no
i    Kevin    8.0         2      no
j    Jonas   19.0         1     yes
k   Suresh   15.5         1     yes

In [41]:
# Câu 12: Sắp xếp df2 tăng dần theo điểm (score)
df2.sort_values(by = 'score')

        name  score  attempts qualify
i      Kevin    8.0         2      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
a  Anastasia   12.5         1     yes
g    Matthew   14.5         1     yes
k     Suresh   15.5         1     yes
c  Katherine   16.5         2     yes
d      James   18.0         3      no
j      Jonas   19.0         1     yes
f    Michael   20.0         3     yes
h      Laura    NaN         1      no

In [46]:
# Câu 13: Thêm cột result vào df2,
# dựa vào dữ liệu của cột'score', nếu dòng nào có điểm >=10 thì giá trị của cột result = 1, ngược lại = 0
def result(score):
   if score >= 10:
    return 1
   else:
      return 0
df2['result'] = df2['score'].map(result)
# In nội dung của dataframe df2
df2

        name  score  attempts qualify  result
a  Anastasia   12.5         1     yes       1
b       Dima    9.0         3      no       0
c  Katherine   16.5         2     yes       1
d      James   18.0         3      no       1
e      Emily    9.0         2      no       0
f    Michael   20.0         3     yes       1
g    Matthew   14.5         1     yes       1
h      Laura    NaN         1      no       0
i      Kevin    8.0         2      no       0
j      Jonas   19.0         1     yes       1
k     Suresh   15.5         1     yes       1

In [51]:
# Câu 14: Trong df2, thay tên 'Emily' thành 'Samantha'
df2.loc[ df2['name'] == 'Emily','name' ]= 'Samantha'
# In lại nội dung của dataframe df2
df2

        name  score  attempts qualify  result
a  Anastasia   12.5         1     yes       1
b       Dima    9.0         3      no       0
c  Katherine   16.5         2     yes       1
d      James   18.0         3      no       1
e   Samantha    9.0         2      no       0
f    Michael   20.0         3     yes       1
g    Matthew   14.5         1     yes       1
h      Laura    NaN         1      no       0
i      Kevin    8.0         2      no       0
j      Jonas   19.0         1     yes       1
k     Suresh   15.5         1     yes       1